### ISSUE TITLE
Configuration does no save upon launch

### ISSUE THREAD

**Issue by Scarlaid** [KessokuTeaTime/Tape-Stop#1] opened 2023-08-04 17:01 UTC
In both version 1.19.4 and 1.20.1, the mod does not save your own settings for next launch, instead reverting to its default
this applies to the `Timeout` configuration, the rest are saved across launches

**Comment by KrLite** [comment] 2023-08-04 17:28
Thanks for reporting! This will be fixed soon.

**Comment by KrLite** [comment] 2023-08-11 04:17
Sadly, I cannot reproduce that issue locally. In all versions the config 'timeoutMs' is loaded and saved properly through both directly modifying the config file and adjusting in the mod menu. I'm not sure what is happening exactly, so I'm afraid that I could not provide further help. Maybe one day it will fix it itself... Who knows

**Closed as not planned by KrLite** 2023-08-11 04:17 UTC
Labels: bug
